name: TESTS

on:
  push:
    branches: ["master"]

permissions:
  contents: read

env:
  MYSQL_ROOT_PASSWORD: root
  MYSQL_USER: user
  MYSQL_PASSWORD: root
  MYSQL_PORT: 3360
  MYSQL_ROOT: root
  DB_HOST: "127.0.0.1"

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}

    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        php-versions: ["5.4"]
        # php-versions: ['5.4', '5.6', '7.3', '7.4', '8.0', '8.1', '8.2', '8.3']

    services:
      mysql:
        image: mysql:5.7
        ports:
          - 3306:3306
        env:
          DB_HOST: ${{ env.DB_HOST }}
          MYSQL_ROOT_PASSWORD: ${{ env.MYSQL_ROOT_PASSWORD }}
          MYSQL_USER: ${{ env.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ env.MYSQL_PASSWORD }}
        volumes:
          - ${{ github.workspace }}/.github/Driver/MySql/my.cnf:/etc/mysql/my.cnf
          - ${{ github.workspace }}/.github/Driver/MySql/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d
        options: --health-cmd "mysqladmin ping -h $DB_HOST -u$MYSQL_USER -p$MYSQL_PASSWORD" --health-interval 20s --health-timeout 10s --health-retries 10

    steps:
      # - name: PHP ${{ matrix.php-versions }} Test on ${{ matrix.operating-system }}
      #   uses: actions/checkout@v3

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: intl #optional
          ini-values: "post_max_size=256M" #optional

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-${{ matrix.php-versions }}

      - name: Install dependencies
        run: |
          cd ${{ github.workspace }}
          composer install --prefer-dist --no-progress

      # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
      # Docs: https://getcomposer.org/doc/articles/scripts.md

      - name: set env
        run: cp tests/.env.example tests/.env

      - name: Run test
        run: vendor/bin/phpunit
